//
// Created by johnny on 7/13/19.
//

#ifndef LEETCODE_FLATTEN_BINARY_TREE2LINKED_LIST_H
#define LEETCODE_FLATTEN_BINARY_TREE2LINKED_LIST_H
int flatten();
#endif //LEETCODE_FLATTEN_BINARY_TREE2LINKED_LIST_H
