//
// Created by johnny on 7/6/19.
//

#ifndef LEETCODE_LOWEST_COMMONANCE_ANCESTOR_H
#define LEETCODE_LOWEST_COMMONANCE_ANCESTOR_H
int lowestCommonAncestor();
#endif //LEETCODE_LOWEST_COMMONANCE_ANCESTOR_H
